---
- file: path=~/.bin
        state=directory

- include: vim.yml
- include: zsh.yml

### Other dotfiles
- copy: dest=~/.{{ item }}
        src={{ item }}
  with_items:
  - gitconfig
  - hgrc
  - tmux.conf
  - tmux.theme.conf
  - screenrc

# this file needs to exist, but it just for local customizations
- file: path=~/.tmux.local state=touch

- yum: name={{ item }} state=latest
  sudo: true
  with_items:
  - git
  - tig
  - mercurial
  - vim-enhanced
  - screen
  - tmux
  - ack
  - bind-utils
  - bzr
  - ccze
  - htop
  - iotop
  - ldns-utils
  - mosh
  - nc
  - nload
  - ntpdate
  - openssh-clients
  - pigz
  - pv
  - ranger
  - rsync
  - strace
  - svn
  - tar
  - traceroute
  - xz
  tags:
    - packages
