---
- yum: name=zsh state=latest
  sudo: true
  tags:
    - packages

### Install all the ZSH plugins & such
- name: Determining username
  shell: whoami
  register: whoami

- name: Changing the default shell to zsh
  sudo: True
  user: shell=/usr/bin/zsh
        user={{ whoami.stdout }}

- file: state=directory
        name={{ item }}
  with_items:
    - ~/.zsh
    - ~/.zsh/custom

- git: repo=https://github.com/sorin-ionescu/prezto.git
       dest=~/.zsh/.zprezto

- git: repo=https://github.com/rupa/z.git
       dest=~/.zsh/z_cd_jumper

- git: repo=https://github.com/zsh-users/zaw.git
       dest=~/.zsh/custom/zaw

- copy: src=zsh/{{ item }}
        dest=~/.zsh/.{{ item }}
  with_items:
    - zlogin
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- file: path=~/.zsh/.zhistory
- file: path=~/.zsh/.zcompdump

- copy: src=zsh/{{ item }}
        dest=~/.zsh/custom/{{ item }}
  with_items:
    - _task
    - prompt
    - init.zsh

- copy: src=zsh/functions dest=~/.zsh

- file: state=directory name=~/.zsh/.zcompcache

- file: src=~/.zsh/{{ item }}
        dest=~/{{ item }}
        state=link
  with_items:
    - .zcompcache
    - .zcompdump
    - .zhistory
    - .zlogin
    - .zpreztorc
    - .zprezto
    - .zprofile
    - .zshenv
    - .zshrc

- file: src=~/.zsh/custom/prompt
        dest=~/.zprezto/modules/prompt/functions/prompt_ryansb_setup
        state=link

- file: src=~/.zsh/custom
        dest=~/.zprezto/modules/custom
        state=link

- file: path=~/.bin
        state=directory

### Other dotfiles
- yum: name={{ item }} state=latest
  sudo: true
  with_items:
  - git
  - tig
  - mercurial
  - vim-enhanced
  - screen
  - tmux
  tags:
    - packages

- copy: dest=~/.{{ item }}
        src={{ item }}
  with_items:
  - gitconfig
  - hgrc
  - tmux.conf
  - tmux.theme.conf
  - screenrc

# this file needs to exist, but it just for local customizations
- file: path=~/.tmux.local

- include: vim.yml
